services:

    makinacorpus.drupal_database_collector:
        class: MakinaCorpus\Drupal\Sf\DataCollector\DrupalDatabaseDataCollector
        arguments: ["@database", '@?debug.stopwatch']
        tags: [{ name: data_collector, template: "module:sf_dic:Profiler/database.html.twig", id: drupal_database}]
